### ISSUE TITLE
Group list does not return correct result for different use cases

### ISSUE THREAD

**Issue by aberbenni** [xamul-it/group-buy#21]
Use cases:
1. Anonymous user (not logged in) _**expected behavior ->**_ list all public groups (no private groups)
    _Controller_: [GroupController](https://github.com/xamul-it/group-buy/blob/master/grails-app/controllers/gb/rest/v1/GroupController.groovy)  _Action_: index
2. App user (logged in) _**expected behavior ->**_ list all public groups and private groups of which the user is a member or owner (the latter first)
    _Controller_: [GroupController](https://github.com/xamul-it/group-buy/blob/master/grails-app/controllers/gb/rest/v1/GroupController.groovy)  _Action_: index

**Comment by xamul-it** [comment]
Reviewed logic, should be fine:
http://localhost:8080/api/v1/groups?max=1&offset=1

**Comment by aberbenni** [comment]
In use case 2 public groups are missing, only groups of which user is member are shown.
Let me clarify the specification
- list **all public groups** of which the user is **not** a member or owner
- list **private groups** of which the user is a **member** or **owner** 
- if possible use this order in output:
             1. owned
             2. member
             3. others (public)

**Comment by xamul-it** [comment]
Partially fixed, missing groups of which a user is member.

**Comment by xamul-it** [comment]
Fixed
