### ISSUE TITLE
Group count does not return correct result for different use cases

### ISSUE THREAD

**Issue by aberbenni** [xamul-it/group-buy#22]
Use cases:
1. Anonymous user (not logged in) _**expected behavior ->**_ count all public groups (no private groups)
    _Controller_: [GroupController](https://github.com/xamul-it/group-buy/blob/master/grails-app/controllers/gb/rest/v1/GroupController.groovy)  _Action_: index _Header_: X-Pagination-Total
2. App user (logged in) _**expected behavior ->**_ count all public groups and private groups of which the user is a member or owner
    _Controller_: [GroupController](https://github.com/xamul-it/group-buy/blob/master/grails-app/controllers/gb/rest/v1/GroupController.groovy)  _Action_: index _Header_: X-Pagination-Total

**Comment by aberbenni** [comment]
Related to https://github.com/xamul-it/group-buy/issues/21

**Comment by xamul-it** [comment]
fixed:

{"Header risposta (151 B)":{"headers":[{"name":"Content-Type","value":"application/json;charset=UTF-8"},{"name":"Date","value":"Sun, 13 Sep 2020 08:14:20 GMT"},{"name":"Transfer-Encoding","value":"chunked"},{"name":"X-Pagination-Total","value":"6"}]}}

**Comment by aberbenni** [comment]
See https://github.com/xamul-it/group-buy/issues/21#issuecomment-694962922

**Comment by xamul-it** [comment]
Fixed like #21
