### ISSUE TITLE
Footer content

### ISSUE THREAD

**Issue by aberbenni** [xamul-it/group-buy#24]
Prepare footer content and decide which elements to keep and which to remove.

**Comment by xamul-it** [comment]
Updated theme footer with basic information.

All social info are hidden by now, will be enabled later on.

**Comment by xamul-it** [comment]
uodated file is main\navigation\_theme-footer.gsp.

Is it the only one to be updated?

**Comment by aberbenni** [comment]
File is: [_theme-footer.gsp](https://github.com/xamul-it/group-buy/blob/master/grails-app/views/navigation/_theme-footer.gsp).
