### ISSUE TITLE
GroupMember

### ISSUE THREAD

**Issue by xamul-it** [xamul-it/group-buy#27]
add new member domain with:
- subscription date
- status
- last status change

**Comment by aberbenni** [comment]
Use cases for members list calls.

`/api/v1/groups/[group id]/members` api calls

- [ ] _**base**_:

max: max # of items to show
offset: start from item #
`/api/v1/groups/[group id]/members?max=4&offset=0
`

- [ ] _**sort**_:

sort: sort by field
order: asc / desc order
`/api/v1/groups/[group id]/members?max=4&offset=0&sort=name&order=asc
`

- [ ] _**filter by status** (id)_:

groupStatusId: id of status
`/api/v1/groups/[group id]/members?max=4&offset=0&groupStatusId=2
`

- [ ] **_search by text_**:

q: query text (on name field)
`/api/v1/groups/[group id]/members?max=4&offset=0&q=[query text]
`

- [ ] _**search by text and status** (id)_:

`/api/v1/groups/[group id]/members?max=4&offset=0&q=[query text]&groupStatusId=2
`

**Comment by xamul-it** [comment]
Implemented base version, switch other tasks to enhancements, need qith huge number of members
