### ISSUE TITLE
Groups api query 

### ISSUE THREAD

**Issue by aberbenni** [xamul-it/group-buy#30]
Use cases for group list calls.

`/api/v1/groups` api calls

- [ ] _**base**_:

max: max # of items to show
offset: start from item #
`/api/v1/groups?max=4&offset=0
`

- [ ] _**sort**_:

sort: sort by field
order: asc / desc order
`/api/v1/groups?max=4&offset=0&sort=creationDate&order=asc
`

- [ ] _**order by position** (special case)_:

sort: fixed value '**nearest**'
latitude: latitude of position
longitude: longitude of position
`/api/v1/groups?max=4&offset=0&sort=nearest&latitude=45.4668&longitude=9.1905
`

- [ ] **_search by text_**:

q: query text
`/api/v1/groups?max=4&offset=0&q=[query text]
`

- [ ] _**search by position coordinates**_:

latitude: latitude of position
longitude: longitude of position
`/api/v1/groups?max=4&offset=0&latitude=45.4668&longitude=9.1905
`

- [ ] _**search by text and category** (id)_:

categoryId: id of category
`/api/v1/groups?max=4&offset=0&q=[query text]&categoryId=8
`

- [ ] _**search by position coordinates and category** (id)_:

latitude: latitude of position
longitude: longitude of position
`/api/v1/groups?max=4&offset=0&latitude=45.4668&longitude=9.1905&categoryId=7
`

- [ ] _**search by text, position coordinates and category** (id)_:

`/api/v1/groups?max=4&offset=0&q=[query text]&latitude=45.4668&longitude=9.1905&categoryId=1
`

- [ ] _**search by text, position coordinates and category** (id) **with sort**_:

`/api/v1/groups?max=4&offset=0&sort=creationDate&order=asc&q=[query text]&latitude=45.4668&longitude=9.1905&categoryId=2`

**Comment by xamul-it** [comment]
Tested should work everithing.
Changed 'q' in 'src'
