### ISSUE TITLE
Difetti grafici

### ISSUE THREAD

**Issue by xamul-it** [xamul-it/group-buy#32]
- [x]  flag remember me si sovrappone sulla scritta 
- [ ]  la frecca del elenco categorie nella maschera di ricerca non ha stile ed è troppo piccola

**Comment by aberbenni** [comment]
Commit 4e24595dcb41bbd6486a87d1914c0d59b171c614 (remember me)

**Comment by aberbenni** [comment]
commit fbb4f22d765bd7c1a85881f6a2c73daba0226e2f (dropdown)
