### ISSUE TITLE
java.lang.NullPointerException: Cannot get property 'id' on null object [order.group]

### ISSUE THREAD

**Issue by aberbenni** [xamul-it/group-buy#44]
Fetching order /api/v1/orders/{hash}.json without being logged in causes java.lang.NullPointerException.

![Screenshot_2020-11-06 Grails Runtime Exception](https://user-images.githubusercontent.com/1632412/98360267-cb361800-2029-11eb-8b37-616b35e3be6f.jpg)

**Comment by xamul-it** [comment]
fixed, was related to anonymous users
