### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by xamul-it** [xamul-it/group-buy#58]
Registration form doesn't show error messages and user get stuck on form:

- [ ] Password must have at least one letter, number, and special character: !@#$%^&
- [ ] Invalid email 
- [ ] Duplicate user
- [ ] Duplicate email

**Comment by aberbenni** [comment]
@xamul-it 

Invalid email means _Invalid email synta_x?

What about activating XHR for Spring security?

**Comment by aberbenni** [comment]
There is no Duplicate email error in s2ui.
