### ISSUE TITLE
Documentazione parametri elenco negozi /supplier

### ISSUE THREAD

**Issue by aberbenni** [xamul-it/group-buy#7]
Quali sono i parametri da passare per paginare l'elenco `/supplier`? Ma anche gli altri in generale.

**Comment by xamul-it** [comment]
Nelle response viene impostato l'header X-Pagination-Total

Il parametro max per numero record da recuperare
Il parametro start per il record iniziale


response.setHeader('X-Pagination-Total', groupService.count().toString())
