### ISSUE TITLE
Extra info for groups

### ISSUE THREAD

**Issue by xamul-it** [xamul-it/group-buy#71]
Add a service with the following information:

- Number of active subscribers
- Number of active orders 
- Number of total orders

**Comment by aberbenni** [comment]
Proposal: add activeOrders, totalOrders, activeSubscribers fields managed by beforeInsert and beforeUpdate Gorm events

**Comment by aberbenni** [comment]
Recalculate values on every update event to minimize misalignements.

**Comment by xamul-it** [comment]
add data on tables and calculate them in "before update" or trigger on db
