### ISSUE TITLE
Order voice editing

### ISSUE THREAD

**Issue by aberbenni** [xamul-it/group-buy#86]
Order voice editing UI is not working even for owner user

**Comment by aberbenni** [comment]
@xamul-it this is a back-end bug:
API `$SERVER/api/v1/groups/XX/orders/YY` returns JSON object with `isOwner=false`
API `$SERVER/api/v1/groups/XX/orders/YY/voices` returns JSON object without `isOwner` field

**Comment by xamul-it** [comment]
user information is present, can we make a match in the FE currentUser.id=user id=?

**Comment by aberbenni** [comment]
fixed in 7eb029b
